### ISSUE TITLE
Set up cabal file and tests

### ISSUE THREAD

**Issue by snowleopard** [tuura/process-mining#2]

**Comment by jrbeaumont** [comment]
What would you like in the the way of tests?

**Comment by snowleopard** [comment]
@jrbeaumont As a start, it would be great to test the concurrency oracle `oracleMokhovCarmona` on several simple examples in a top-level file named `Test.hs`.

For example, given log `abc acb` the oracle should determine that `b` and `c` are concurrent.

**Comment by jrbeaumont** [comment]
OK, have a look at my repo:
https://github.com/jrbeaumont/process-mining.git

I have tested this, and it builds correctly on Windows, OS X and Linux, using a simple Test file.

I'm not sure how to set it up so it uses `pgminer.hs", or creates an executable file as this causes the tests to fail, mainly because it fails if a file is not included when attempting to run it.

**Comment by snowleopard** [comment]
Let's not worry about `pgminer` for now. I'll see how we can create an executable without disrupting tests.

**Comment by jrbeaumont** [comment]
OK, I will make the changes suggested in #4
